version: 2
# This is CI job spec for Android project using CircleCI
# See https://circleci.com/docs/2.0/language-android/ for more info.
jobs:
  build:
    # In each job, we have the option of specifying a working_directory.
    # This is the directory into which our code will be checked out,
    # and this path will be used as the default working directory for
    # the rest of the job unless otherwise specified.
    working_directory: ~/code
    docker:
      # We use the CircleCI-provided Android image with the api-25-alpha tag.
      # Our Android Docker images are currently tagged with the suffix -alpha.
      # This is to indicate the images are currently under development and
      # might change in backwards incompatible ways from week to week.
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Build
          command: ./gradlew assembleDebug --info --stacktrace
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests and Checks
          command: ./gradlew ktlintCheck lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          # Stores mobile apk for local testing
          path: app/build/outputs/apk
          destination: mobile-apk
      - store_test_results:
          path: app/build/test-results